objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Log to capture exceptions and errors, more general than the API-specific Sync Logs.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Captures the error message</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Captures the error message</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Contains the record id by which the error was caused, if applicable.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Contains the record id by which the error was caused, if applicable.</inlineHelpText>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Captures the stack trace of the error</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Captures the stack trace of the error</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/Logger.cls
/**
    @author: Dan Thoreson
    @date: 2021-01-05
    @description: Class for creating Error Log records
**/
public with sharing class Logger {

    public static void insertErrorLog(Exception ex, Id recordId) {
        insert createErrorLog(ex.getStackTraceString(), ex.getMessage(), recordId);
    }

    public static void insertErrorLog(String stackTrace, String message, Id recordId) {
        insert createErrorLog(stackTrace, message, recordId);
    }

    public static Error_Log__c createErrorLog(String stackTrace, String message, Id recordId) {
        return new Error_Log__c(Stack_Trace__c=stackTrace, Message__c=message, Record_Id__c=recordId);
    }
}